version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: application 
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./php/:/usr/local/etc/php
    networks:
      - app-network

    # Postgres Service
  postgresql:
    image: postgres
    container_name: database 
    tty: true
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes: 
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webservice
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

    # Redis Service
  redis:
      image: redis:alpine
      container_name: cache-server 
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports:
        - "6379:6379"

#Volumes
volumes:
  dbdata: 
    driver: local


#Docker Networks
networks:
  app-network:
    driver: bridge
